warmup4: warmup4.h warmup4.c warmup4_main.c warmup4_provided.h warmup4_provided.c
	-clang -Wall -o warmup4 warmup4.c warmup4_main.c warmup4_provided.c -lpng

hw4: hw4.h hw4.c hw4_main.c hw4_provided.h hw4_provided.c
	-clang -Wall -o hw4 hw4.c hw4_main.c hw4_provided.c -lm
