hw7_1: bst.h bst.c heap.h heap.c llist.h llist.c word.h word.c hw6.h hw6.c hw7_part1_main.c
	-clang -o hw7_1 bst.c heap.c llist.c word.c hw6.c hw7_part1_main.c

hw7_2: bst.h bst.c heap.h heap.c llist.h llist.c word.h word.c hw6.h hw6.c compress.h compress.c hw7_2_main.c
	-clang -o hw7_2 bst.c heap.c llist.c word.c hw6.c compress.c hw7_2_main.c
